CREATE DATABASE FilmLit;
USE FilmLit;

CREATE TABLE USUARIO (
	ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_USUARIO VARCHAR(255) UNIQUE NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    TIPO_USUARIO VARCHAR(60) DEFAULT 'BASE',
    ACTIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE PERFIL (
    ID_PERFIL INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    FOTO_PERFIL VARCHAR(255)NULL,
    NOMBRE VARCHAR(255) NULL,
    DESCRIPCION VARCHAR(280) NULL,
    FECHA_NACIMIENTO DATETIME NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE SEGUIDORES_CUENTA (
    ID_SEGUIDO INT,
    ID_SEGUIDOR INT,
    FECHA DATETIME DEFAULT NOW(),
    PRIMARY KEY (ID_SEGUIDO, ID_SEGUIDOR),
    FOREIGN KEY (ID_SEGUIDO) REFERENCES PERFIL(ID_PERFIL) ON DELETE CASCADE,
    FOREIGN KEY (ID_SEGUIDOR) REFERENCES PERFIL(ID_PERFIL) ON DELETE CASCADE
);

CREATE TABLE PUBLICACION (
	ID_PUBLICACION INT PRIMARY KEY AUTO_INCREMENT,
    ID_PERFIL INT,
    DESCRIPCION VARCHAR(255) NOT NULL,
    MULTIMEDIA VARCHAR(255),
    FECHA DATETIME DEFAULT NOW(),
    LIKES INT DEFAULT 0,
    FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID_PERFIL) ON DELETE CASCADE
);

CREATE TABLE LIKES (
    ID_LIKE INT PRIMARY KEY AUTO_INCREMENT,
    ID_PERFIL INT,
    ID_PUBLICACION INT,
    FECHA DATETIME DEFAULT NOW(),
    FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID_PERFIL) ON DELETE CASCADE,
    FOREIGN KEY (ID_PUBLICACION) REFERENCES PUBLICACION(ID_PUBLICACION) ON DELETE CASCADE
);

CREATE TABLE COMENTARIO (
	ID_COMENTARIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PERFIL INT,
    ID_PUBLICACION INT,
    DESCRIPCION VARCHAR(280) NOT NULL,
    FECHA DATETIME DEFAULT NOW(),
    FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID_PERFIL) ON DELETE CASCADE,
    FOREIGN KEY (ID_PUBLICACION) REFERENCES PUBLICACION(ID_PUBLICACION) ON DELETE CASCADE
);

CREATE TABLE MENSAJE_DIRECTO (
    ID_DM INT KEY AUTO_INCREMENT,
    ID_USUARIO_ENVIA INT,
    ID_USUARIO_RECIBE INT,
    MULTIMEDIA VARCHAR(255),
    DESCRIPCION TEXT,
    FECHA DATETIME DEFAULT NOW(),
    FOREIGN KEY (ID_USUARIO_ENVIA) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    FOREIGN KEY (ID_USUARIO_RECIBE) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE LIBRO (
    ID_LIBRO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT ,
    TITULO VARCHAR(255) NOT NULL,
    FECHA_PUBLICACION DATETIME,
    PORTADA VARCHAR(255)
);

CREATE TABLE BIBLIOTECA (
    ID_BIBLIOTECA INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    ID_OBRA INT,
    FECHA DATETIME DEFAULT NOW(),
    ESTADO VARCHAR(100) DEFAULT 'NO EMPEZADO',
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE SALA (
    ID_SALA INT PRIMARY KEY AUTO_INCREMENT,
    ID_PERFIL INT,
    PRIVADO BOOLEAN,
    CONTRASENA VARCHAR(100),
    MULTIMEDIA VARCHAR(255)NULL,
    DESCRIPCION_CORTA VARCHAR(255)NULL,
    NOMBRE VARCHAR(100),
    FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID_PERFIL) ON DELETE CASCADE
);

CREATE TABLE REGISTRO_ACCESO (
    ID_REGISTRO_ACCESO INT PRIMARY KEY AUTO_INCREMENT,
    ID_SALA INT,
    ID_PERFIL INT,
    FECHA DATETIME DEFAULT NOW(),
    FOREIGN KEY (ID_SALA) REFERENCES SALA(ID_SALA) ON DELETE CASCADE,
    FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID_PERFIL) ON DELETE CASCADE
);

CREATE TABLE MENSAJE (
    ID_MENSAJE INT PRIMARY KEY AUTO_INCREMENT,
    ID_REGISTRO_ACCESO INT,
    DESCRIPCION VARCHAR(280),
    MULTIMEDIA VARCHAR(255),
    FECHA DATETIME DEFAULT NOW(),
    FOREIGN KEY (ID_REGISTRO_ACCESO) REFERENCES REGISTRO_ACCESO(ID_REGISTRO_ACCESO) ON DELETE CASCADE
);

CREATE TABLE REPORTE (
    ID_REPORTE INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    ID_MENSAJE INT,
    ID_PUBLICACION INT,
    ID_COMENTARIO INT,
    ID_DM INT,
    ID_SALA INT,
    DESCRIPCION VARCHAR(255) NOT NULL,
    FECHA DATETIME DEFAULT NOW(),
    ESTADO VARCHAR(100) DEFAULT 'POR REVISAR',
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    FOREIGN KEY (ID_MENSAJE) REFERENCES MENSAJE(ID_MENSAJE) ON DELETE CASCADE,
    FOREIGN KEY (ID_PUBLICACION) REFERENCES PUBLICACION(ID_PUBLICACION) ON DELETE CASCADE,
    FOREIGN KEY (ID_COMENTARIO) REFERENCES COMENTARIO(ID_COMENTARIO) ON DELETE CASCADE,
    FOREIGN KEY (ID_DM) REFERENCES MENSAJE_DIRECTO(ID_DM) ON DELETE CASCADE,
    FOREIGN KEY (ID_SALA) REFERENCES SALA(ID_SALA) ON DELETE CASCADE
);

CREATE TABLE NOTICIA (
    ID_NOTICIA INT PRIMARY KEY AUTO_INCREMENT,
    TITULAR VARCHAR(255),
    DESCRIPCION LONGTEXT,
    FUENTE VARCHAR(255),
    FECHA DATETIME,
    PORTADA VARCHAR(255)
);